name: Branch Flow Listener
run-name: ${{github.actor}} DO ACTION WITH ${{github.action}}
on:
  pull_request:
    branches:
      - beta
      - 'release/*'
      - '!release/*-dev'
      - '!release/**-test'
  push:
    paths: 
      - 'src/**'
      - "!.github/workflows/**"

######
# TODO:
# - 打印提交的文件路径列表
# - 是否可以不同trigger event 触发不同的 jobs? 还是必须要只在不同的Action 中处理
# - 执行一个自定义的脚本文件
######

jobs:
  Push_Event:
    runs-on: ubuntu-lastest
    if: ${{github.event_name}} == 'push'
    steps:
      - name: push event step name
        run: echo 'oooooo'
      - run: echo ${{github.ref_name}}-${{github.event_path}}
  Pull-Request:
    runs-on: ubuntu-latest
    if: ${{github.event_name}} == 'pull_request'
    steps:
      - name: pull request step name
        run: echo "sosoososo"
      - run: |
          echo "all github constants ${{github.event_name}}-${{github.ref_type}}"
          echo  ${{github.event_path}}
  
  
    
 
